version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: booklify_db
    environment:
      - DATABASE_USERNAME={DATABASE_USERNAME}
      - DATABASE_PASSWORD={DATABASE_PASSWORD}
      - DATABASE_NAME={DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    networks:
      - my_network

  book-service:
    image: afulvio/booklify-book-service:latest
    container_name: booklify_book_service
    environment:
      - DATABASE_URL={DATABASE_URL}
      - DATABASE_USERNAME={DATABASE_USERNAME}
      - DATABASE_PASSWORD={DATABASE_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
