services:
  postgres:
    image: postgres:latest
    container_name: booklify_db
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    networks:
      - book_service_network

  service-registry:
    image: afulvio/booklify-service-registry:latest
    container_name: booklify_service_registry
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8761:8761"
    networks:
      - book_service_network

  book-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booklify_book_service
    ports:
      - "8080:8080"
    environment:
      eureka.client.serviceUrl.defaultZone: http://service-registry:8761/eureka/
    depends_on:
      - postgres
      - service-registry
    networks:
      - book_service_network

networks:
  book_service_network:
    driver: bridge
