spring:
    application:
        name: book-service
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: pgadmin
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    main:
        web-application-type: servlet

server:
    port: 8080

logging:
    level:
        web: debug

management:
    endpoints:
        web:
            exposure:
                include: '*'

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
        fetchRegistry: true
        register-with-eureka: true