spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://postgres:5432/booklify
    username: postgres
    password: pgadmin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    web-application-type: reactive
  session:
    jdbc:
      initialize-schema: always

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    web: debug