spring:
    application:
        name: book-service
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: pgadmin
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    main:
        web-application-type: reactive

server:
    port: 8080

management:
    endpoints:
        web:
            exposure:
                include: '*'

logging:
    level:
        sql: debug
        org.hibernate.orm.jdbc.bind: trace

springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui
    api-docs:
        enabled: true
        path: /api-docs