spring:
  application:
    name: "@project.artifactId@"
  datasource:
    url: jdbc:postgresql://localhost:5432/booklify
    username: postgres
    password: pgadmin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  main:
    web-application-type: servlet

server:
  port: 8080

logging:
  level:
    web: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'