spring:
  application:
    name: "@project.artifactId@"
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/booklify}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:pgadmin}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  main:
    web-application-type: servlet

server:
  port: 8080

logging:
  level:
    web: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://service-registry:8761/eureka/}
    fetchRegistry: true
    register-with-eureka: true