name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Maven
        run: 'mvn package -DskipTests'
#        run: 'mvn package -DskipTests'

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag booklify-book-service:latest
