name: Production Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Set up Git user
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build dynamic version
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Update pom.xml version
        run: mvn versions:set -DnewVersion=${{ env.VERSION }} -DgenerateBackupPoms=false

      - name: Update Dockerfile version
        run: sed -i "s/booklify-book-service-[0-9]*\.[0-9]*\.[0-9]*\.jar/booklify-book-service-${{ env.VERSION }}.jar/" Dockerfile

      - name: Commit e push updates
        run: |
          git add pom.xml Dockerfile
          git commit -m "Version updated up to ${{ env.VERSION }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/AFulvio1/booklify-book-service.git HEAD:master

      - name: Create Git tag
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Crea Release su GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: "Released version v${{ env.VERSION }}"
          draft: false
          prerelease: false

      - name: Build with Maven
        run: mvn -B install --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
            --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            -t ghcr.io/afulvio1/booklify-book-service:latest .
          docker tag ghcr.io/afulvio1/booklify-book-service:latest afulvio/booklify-book-service:latest

      - name: Push Docker images
        run: |
          docker push ghcr.io/afulvio1/booklify-book-service:latest
          docker push afulvio/booklify-book-service:latest