name: Github Container

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B install --file pom.xml

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Build Docker image
        run: |
          docker build -t ghcr.io/afulvio1/booklify-book-service:latest .
          docker tag ghcr.io/afulvio/booklify-book-service::latest afulvio/booklify-book-service:latest

      - name: Push Docker images
        run: |
          docker push ghcr.io/afulvio/booklify-book-service:latest
          docker push afulvio/booklify-book-service:latest