name: Github Container

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B install --file pom.xml

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
            IMAGE_NAME="ghcr.io/${{ github.repository }}/booklify-book-service:${{ github.ref_name }}"
            echo "Building Docker image: $IMAGE_NAME"
            docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
            IMAGE_NAME="ghcr.io/${{ github.repository }}/booklify-book-service:${{ github.ref_name }}"
            echo "Pushing Docker image: $IMAGE_NAME"
            docker push $IMAGE_NAME